### ISSUE TITLE
Format change - scrape crash.

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-mddb-2022#56]
![image](https://user-images.githubusercontent.com/876146/157059645-d4e9eea7-ce4e-4c21-af59-5d797f9546ba.png)
![image](https://user-images.githubusercontent.com/876146/157059999-0a21e0a7-ba77-47ea-8f86-3b1ca44f977a.png)

An exception of type 'System.NullReferenceException' occurred in prospect-scraper-mddb-2022.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at prospect_scraper_mddb_2022.Extensions.HtmlNodeCollectionExtensions.FindProspects(HtmlNodeCollection nodes, String todayString, Dictionary`2& schoolImages) in /workspaces/prospect-scraper-mddb-2022/Extensions/HtmlNodeCollectionExtensions.cs:line 56
   at prospect_scraper_mddb_2022.Extensions.StatusContextExtensions.ScrapeYear(StatusContext ctx, HtmlWeb webGet, String scrapeYear, String urlToScrape) in /workspaces/prospect-scraper-mddb-2022/Extensions/StatusContextExtensions.cs:line 77
   at prospect_scraper_mddb_2022.Program.<>c__DisplayClass0_0.<Main>b__0(StatusContext ctx) in /workspaces/prospect-scraper-mddb-2022/Program.cs:line 30
   at Spectre.Console.Status.<>c__DisplayClass14_0.<Start>b__0(StatusContext ctx) in /_/src/Spectre.Console/Live/Status/Status.cs:line 47
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 82

**Comment by zo0o0ot** [comment]
Fixed in #57
